-- MySQL Script generated by MySQL Workbench
-- 11/30/17 11:31:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema passeiraspandodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema passeiraspandodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `passeiraspandodb` DEFAULT CHARACTER SET utf8 ;
USE `passeiraspandodb` ;

-- -----------------------------------------------------
-- Table `passeiraspandodb`.`University`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `passeiraspandodb`.`University` (
  `idUniversity` INT NOT NULL AUTO_INCREMENT,
  `nameUniversity` VARCHAR(45) NULL,
  PRIMARY KEY (`idUniversity`),
  UNIQUE INDEX `nameUniversity_UNIQUE` (`nameUniversity` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `passeiraspandodb`.`Discipline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `passeiraspandodb`.`Discipline` (
  `idDiscipline` INT NOT NULL AUTO_INCREMENT,
  `nameDiscipline` VARCHAR(45) NULL,
  `descriptionDiscipline` VARCHAR(45) NULL,
  PRIMARY KEY (`idDiscipline`),
  UNIQUE INDEX `nameDiscipline_UNIQUE` (`nameDiscipline` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `passeiraspandodb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `passeiraspandodb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `username` VARCHAR(15) NULL,
  `password` VARCHAR(15) NULL,
  `semester` VARCHAR(45) NULL,
  `University_idUniversity` INT NOT NULL,
  `Discipline_idDiscipline` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_User_University1_idx` (`University_idUniversity` ASC),
  INDEX `fk_User_Discipline1_idx` (`Discipline_idDiscipline` ASC),
  CONSTRAINT `fk_User_University1`
    FOREIGN KEY (`University_idUniversity`)
    REFERENCES `passeiraspandodb`.`University` (`idUniversity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Discipline1`
    FOREIGN KEY (`Discipline_idDiscipline`)
    REFERENCES `passeiraspandodb`.`Discipline` (`idDiscipline`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `passeiraspandodb`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `passeiraspandodb`.`Course` (
  `idCourse` INT NOT NULL AUTO_INCREMENT,
  `nameCourse` VARCHAR(45) NULL,
  `maxSemester` VARCHAR(45) NULL,
  `Discipline_idDiscipline` INT NOT NULL,
  PRIMARY KEY (`idCourse`),
  UNIQUE INDEX `nameCourse_UNIQUE` (`nameCourse` ASC),
  INDEX `fk_Course_Discipline1_idx` (`Discipline_idDiscipline` ASC),
  CONSTRAINT `fk_Course_Discipline1`
    FOREIGN KEY (`Discipline_idDiscipline`)
    REFERENCES `passeiraspandodb`.`Discipline` (`idDiscipline`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `passeiraspandodb`.`Archive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `passeiraspandodb`.`Archive` (
  `idArchive` INT NOT NULL AUTO_INCREMENT,
  `nameArchive` VARCHAR(20) NULL,
  `descriptionArchive` VARCHAR(45) NULL,
  `Archivecol` VARCHAR(45) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idArchive`),
  INDEX `fk_Archive_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Archive_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `passeiraspandodb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `passeiraspandodb`.`University_has_Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `passeiraspandodb`.`University_has_Course` (
  `University_idUniversity` INT NOT NULL,
  `Course_idCourse` INT NOT NULL,
  PRIMARY KEY (`University_idUniversity`, `Course_idCourse`),
  INDEX `fk_University_has_Course_Course1_idx` (`Course_idCourse` ASC),
  INDEX `fk_University_has_Course_University_idx` (`University_idUniversity` ASC),
  CONSTRAINT `fk_University_has_Course_University`
    FOREIGN KEY (`University_idUniversity`)
    REFERENCES `passeiraspandodb`.`University` (`idUniversity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_University_has_Course_Course1`
    FOREIGN KEY (`Course_idCourse`)
    REFERENCES `passeiraspandodb`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
